apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: developer-portal
  description: Zuse Systems internal developer portal
  annotations:
    github.com/project-slug: zuse-cc/developer-portal
    # backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: developer-enablement
  lifecycle: alpha
  system: platform-tooling
